//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary
    {
        public int ReservationId { get; set; }
        public Nullable<int> PassengerId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        public virtual FlightSchedule FlightSchedule { get; set; }
        public virtual User User { get; set; }
    }
}
